    - name: Main-Playbook
      hosts: debianserver
      remote_user: "{{ user_name }}"
      gather_facts: yes
      vars_files: ./group_vars/variables.yml

      roles:
        - ssh
        - docker
