    - name: install dependencies
      become: true
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - ca-certificates
        - curl
        - gnupg-agent
    - name: add GPG key
      become: true
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
    - name: add docker repository to apt
      become: true
      apt_repository:
        repo: deb https://download.docker.com/linux/debian bullseye stable
        state: present
    - name: install docker
      become: true
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
    - name: check docker is active
      service:
        name: docker
        state: started
        enabled: yes
    - name: Ensure group "docker" exists
      ansible.builtin.group:
        name: docker
        state: present
    - name: adding user to docker group
      become: true
      user:
        name: "{{ user_name }}"
        groups: docker
        append: yes
